import bs4
import errno
import functools
import itertools
import json
import multiprocessing
import openai
import os
import pprint
import random
import subprocess
import time
from dotenv import load_dotenv
from http.server import BaseHTTPRequestHandler, HTTPServer

load_dotenv()

FIFO_PATH = "/tmp/my_fifo"

api_key = os.environ.get('API_KEY')
client = openai.OpenAI(api_key=api_key)

MAX_TOKENS = 3000
MAX_NUM_HEADLINES = 30

PROMPT_BASE = """I'm going to write a list of news headlines. Score each category by the probability that a psychologist will have clients in tears about these headlines during their next session. Then, in the summary string, briefly explain what specifically is likely to stress out, concern, or alarm people about these headlines — and why it's getting under their skin.

POLITICAL: Probability between 0.0 and 1.0 that a psychologist will have clients crying about these political headlines in their next session.
GLOBAL: Probability between 0.0 and 1.0 that a psychologist will have clients crying about these global events in their next session.
WAR / CONFLICT: Probability between 0.0 and 1.0 that a psychologist will have clients crying about these conflicts or acts of violence in their next session.
SCIENCE AND TECHNOLOGY: Probability between 0.0 and 1.0 that a psychologist will have clients crying about these science and technology headlines in their next session.
ECONOMY: Probability between 0.0 and 1.0 that a psychologist will have clients crying about these economic headlines in their next session.
SPORTS AND ENTERTAINMENT: Probability between 0.0 and 1.0 that a psychologist will have clients crying about these sports and entertainment headlines in their next session.
OVERALL: Probability between 0.0 and 1.0 that a psychologist will have clients crying about today's overall news cycle in their next session.

Be extremely judicious with high scores. Only score categories above 0.4 if there is genuinely alarming content.

Write each summary as a concise, direct explanation of what's freaking people out and why — not reassurance, not therapy-speak. Be specific about the threat or source of anxiety. Use wit and a touch of snark.

Reply ONLY WITH A VALID JSON. The JSON is a dictionary, keyed by category with array values, consisting of a floating point score AND A SHORT STRING explaining what's alarming or stressful about these headlines. ONLY reply using JSON. DO NOT include anything other than JSON. Your response will be interpreted as JSON so DO NOT REPLY WITH ANYTHING OTHER THAN VALID JSON.

Example of a valid response:
{"POLITICAL": [0.12, "The usual partisan noise. Nothing that will change anyone's actual life, but everyone will act like it might."], "GLOBAL": [0.05, "Low-grade geopolitical friction with no imminent escalation. Background hum, not a crisis."], "WAR / CONFLICT": [0.0, "Nothing notable. Rare."], "SCIENCE AND TECHNOLOGY": [0.45, "A major AI capability jump is making people question job security and the nature of creative work. The concern is legitimate."], "ECONOMY": [0.08, "Markets did their normal thing. Nothing that should ruin anyone's week."], "SPORTS AND ENTERTAINMENT": [0.02, "A celebrity scandal. Culturally noisy, personally irrelevant to almost everyone."], "OVERALL": [0.15, "A low-stakes news day. The volume is high but the actual threat level is minimal."]}

The headlines are:

"""

FIX_JSON_PROMPT = """Extract the JSON text from this text. DO NOT respond with anything other than JSON. Your response will be interpreted as JSON so DO NOT REPLY WITH ANYTHING OTHER THAN VALID JSON.

"""

def read_new_news():
    print('reading NEW news')
    result = subprocess.run(
            ["curl", "http://68k.news/"],
            capture_output=True, text=True, check=True)
    return result.stdout


def read_old_news():
    print('reading old news')
    with open('68k.html', 'r') as f:
        return f.read()


def extract_google_news_headlines(html_content):
    soup = bs4.BeautifulSoup(html_content, 'html.parser')

    articles = []
    for link in soup.find_all('a'):
        href = link.get('href')
        if href is not None and href.startswith('./articles/') and link.text != '':
            articles.append(link.text)

    return articles


def extract_68k_news_headlines(html_content):
    soup = bs4.BeautifulSoup(html_content, 'html.parser')

    articles = []
    for headline in itertools.islice(soup.find_all('h3'), MAX_NUM_HEADLINES):
        articles.append(headline.text)

    return articles

def request_chatgpt(prompt):
    """
    Sends a request to ChatGPT API using the openai package.

    :param prompt: The prompt to send to ChatGPT.
    :return: The text generated by ChatGPT.
    """

    print('requesting gpt-5.2: ' + prompt)
    completion = client.chat.completions.create(
        model="gpt-5.2",
        messages=[
            {
                "role": "user",
                "content": prompt
            },
        ],
    )
    return completion.choices[0].message.content


def create_fifo():
    """ Creates a FIFO if it doesn't already exist """
    try:
        os.mkfifo(FIFO_PATH)
    except OSError as oe:
        if oe.errno != errno.EEXIST:
            raise


def is_file_old(fname, max_age=300):
    return time.time() - os.stat("news.json").st_mtime > max_age


def get_headlines_json():
    # Check if the file is older than 5 minutes
    if is_file_old("news.json"):
        print('file is old')
        # Perform a non-blocking write to the FIFO
        try:
            fifo_fd = os.open(FIFO_PATH, os.O_WRONLY | os.O_NONBLOCK)
            os.write(fifo_fd, b'1')
            os.close(fifo_fd)
        except OSError as oe:
            if oe.errno != errno.EAGAIN:
                raise

    # Read and return the contents of the file
    with open("news.json", 'r') as file:
        json_str = file.read()
        return json.loads(json_str)


class SimpleHTTPRequestHandler(BaseHTTPRequestHandler):

    def do_GET(self):
        if self.path == '/':
            self.send_response(200)
            self.send_header('Content-type', 'text/html')
            self.end_headers()
            with open('index.html', 'rb') as file:
                self.wfile.write(file.read())
        elif self.path == '/style.css':
            self.send_response(200)
            self.send_header('Content-type', 'text/css')
            self.end_headers()
            with open('style.css', 'rb') as file:
                self.wfile.write(file.read())
        elif self.path == '/script.js':
            self.send_response(200)
            self.send_header('Content-type', 'application/javascript')
            self.end_headers()
            with open('script.js', 'rb') as file:
                self.wfile.write(file.read())
        elif self.path == '/news.json':
            self.send_response(200)
            self.send_header('Content-type', 'application/json')
            self.end_headers()
            headlines = get_headlines_json()
            self.wfile.write(json.dumps(headlines).encode())
        else:
            self.send_response(404)
            self.end_headers()
            self.wfile.write(b'404 Not Found')


def run_server(server_class=HTTPServer, handler_class=SimpleHTTPRequestHandler):
    server_address = ('', 8000)
    httpd = server_class(server_address, handler_class)
    print("Server started at http://localhost:8000")
    httpd.serve_forever()


def headline_refresher():
    """ Consumer process that reads from the FIFO """
    while True:
        with open(FIFO_PATH, 'r') as fifo:
            print("Consumer: waiting for data")
            for line in fifo:
                print("Consumer: received data:", line.strip())

            if not is_file_old("news.json"):
                print('file is not old')
                continue

            with open("new.news.json", "w") as h_json:
                headlines = '\n'.join(extract_68k_news_headlines(read_new_news()))
                print(headlines)
                prompt = PROMPT_BASE + headlines
                gpt_json = request_chatgpt(prompt)
                # Sometimes the model returns a bit more than JSON, so we
                # have to Attempt to parse the json, and use chatgpt to fix it
                try:
                    print('attempting to parse json')
                    json.loads(gpt_json)
                    print('json is good')
                except json.JSONDecodeError as e:
                    print('attempting to fix json')
                    prompt = FIX_JSON_PROMPT + gpt_json
                    gpt_json = request_chatgpt(prompt)
                    print('fixed? ' + gpt_json)
                h_json.write(gpt_json)
                pprint.pprint(gpt_json)

            # rename for atomic swap
            os.rename("new.news.json", "news.json")


def main():
    #print('\n'.join(extract_68k_news_headlines(read_old_news())))

    create_fifo()

    # Create server and headline_refresher processes
    p = multiprocessing.Process(target=run_server)
    c = multiprocessing.Process(target=headline_refresher)

    # Start the processes
    p.start()
    c.start()
    print(f'Started. server pid: {p.pid} refresher pid: {c.pid}')

    # Wait for the processes to finish (they won't in this case, as they loop forever)
    p.join()
    c.join()


if __name__=='__main__':
    main()
